# Generated by Django 4.2.30 on 2026-04-27 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0004_keyword_movie_keywords"),
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="liked_genre",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="liked_performances",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="liked_story",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="would_rewatch",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="is_positive",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("user", "movie")},
        ),
    ]
